baseURL = 'https://gn.tc/'
languageCode = 'en-us'
title = 'GN.TC (Good Night Take Care âœ¨)'
theme = 'PaperMod'

[pagination]
  pagerSize = 10

[params]
  title = 'GN.TC - Good Night Take Care'
  author = "GNSD Team"
  defaultTheme = "auto"
  ShowReadingTime = true
  ShowShareButtons = false
  ShowPostNavLinks = true
  comments = false
  hideFooter = true
  #homeInfoParams = { Title = "GN.TC ðŸ’«", Content = "Someone thought of you and sent you a GN.TC â€” short for Good Night, Take Care" }
  mainSections = ["posts"]

[markup.goldmark.renderer]
  unsafe = true
